[package]
name = "panicit"
version = "0.1.0"
authors = ["Andrew Dirksen <andrew@dirksen.com>"]
edition = "2018"

[lib]
name = "panicit"
crate-type = ["cdylib"]

[dependencies]

# [profile.release]
# opt-level = 0
